using Bookstore.Api.Data;
using Bookstore.Api.Models;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// Enables OpenAPI metadata for easier endpoint testing in development.
builder.Services.AddOpenApi();
// Registers EF Core so we can query Bookstore.sqlite through BookstoreContext.
builder.Services.AddDbContext<BookstoreContext>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("BookstoreDb")));

// Allows the React app (local + Azure) to call this API. Configure origins in appsettings or env.
var corsOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
                  ?? new[] { "http://localhost:5173" };
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowClient", policy =>
        policy.WithOrigins(corsOrigins).AllowAnyHeader().AllowAnyMethod());
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseCors("AllowClient");

// Returns a paged list of books plus total count for client-side pagination UI.
app.MapGet("/api/books", async (
    BookstoreContext context,
    int pageSize = 5,
    int pageNum = 1,
    string sort = "asc",
    // Comma-separated list of categories to filter by (e.g., "Biography,Self-Help").
    // If omitted or empty, results include all categories.
    string? categories = null) =>
{
    // Guards against invalid query values and very large page sizes.
    var normalizedPageSize = Math.Clamp(pageSize, 1, 100);
    var normalizedPageNum = Math.Max(pageNum, 1);
    var sortDescending = string.Equals(sort, "desc", StringComparison.OrdinalIgnoreCase);

    // Parses the categories filter into a list for LINQ "IN (...)" style filtering.
    var categoryList = string.IsNullOrWhiteSpace(categories)
        ? new List<string>()
        : categories.Split(',', StringSplitOptions.TrimEntries)
            .Where(c => !string.IsNullOrWhiteSpace(c))
            .ToList();

    // Filters first, then sorts/paginates.
    var filteredQuery = context.Books.AsQueryable();
    if (categoryList.Count > 0)
    {
        filteredQuery = filteredQuery.Where(b => categoryList.Contains(b.Category));
    }

    var sortedQuery = sortDescending
        ? filteredQuery.OrderByDescending(b => b.Title)
        : filteredQuery.OrderBy(b => b.Title);

    // Count after filtering, then return only the requested page.
    var totalBooks = await filteredQuery.CountAsync();
    var books = await sortedQuery
        .Skip((normalizedPageNum - 1) * normalizedPageSize)
        .Take(normalizedPageSize)
        .ToListAsync();

    return Results.Ok(new
    {
        books,
        totalBooks
    });
});

// Used to populate the category filter UI.
app.MapGet("/api/categories", async (BookstoreContext context) =>
{
    var categories = await context.Books
        .Select(b => b.Category)
        .Distinct()
        .OrderBy(c => c)
        .ToListAsync();

    return Results.Ok(categories);
});

// Create a book (BookID is generated by SQLite AUTOINCREMENT).
app.MapPost("/api/books", async (BookInputDto dto, BookstoreContext context) =>
{
    var validationError = dto.GetValidationError();
    if (validationError is not null)
    {
        return Results.BadRequest(new { error = validationError });
    }

    var book = new Book
    {
        Title = dto.Title.Trim(),
        Author = dto.Author.Trim(),
        Publisher = dto.Publisher.Trim(),
        Isbn = dto.Isbn.Trim(),
        Classification = dto.Classification.Trim(),
        Category = dto.Category.Trim(),
        PageCount = dto.PageCount,
        Price = dto.Price,
    };

    context.Books.Add(book);
    await context.SaveChangesAsync();

    return Results.Created($"/api/books/{book.BookId}", book);
});

// Update an existing book by id.
app.MapPut("/api/books/{id:int}", async (int id, BookInputDto dto, BookstoreContext context) =>
{
    var validationError = dto.GetValidationError();
    if (validationError is not null)
    {
        return Results.BadRequest(new { error = validationError });
    }

    var book = await context.Books.FindAsync(id);
    if (book is null)
    {
        return Results.NotFound();
    }

    book.Title = dto.Title.Trim();
    book.Author = dto.Author.Trim();
    book.Publisher = dto.Publisher.Trim();
    book.Isbn = dto.Isbn.Trim();
    book.Classification = dto.Classification.Trim();
    book.Category = dto.Category.Trim();
    book.PageCount = dto.PageCount;
    book.Price = dto.Price;

    await context.SaveChangesAsync();
    return Results.NoContent();
});

// Delete a book by id.
app.MapDelete("/api/books/{id:int}", async (int id, BookstoreContext context) =>
{
    var book = await context.Books.FindAsync(id);
    if (book is null)
    {
        return Results.NotFound();
    }

    context.Books.Remove(book);
    await context.SaveChangesAsync();
    return Results.NoContent();
});

app.Run();
